In [5]:
import numpy as np
from common.layers import Affine, Sigmoid, SoftmaxWithLoss


class TwoLayersNet:
    def __init__(self, in_size, hiddne_size, out_size) -> None:
        I, H, O = in_size, hiddne_size, out_size
        W1 = 0.01*np.random.randn(I, H)
        b1 = np.zeros(H)
        W2 = 0.01*np.random.randn(H, O)
        b2 = np.zeros(O)

        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        self.loss_layer = SoftmaxWithLoss()

        self.params, self.grads = [], []
        for layer in self.layers:
            self.params += layer.params
            self.grads += layer.grads

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

    def forward(self, x, t):
        score = self.predict(x)
        loss = self.loss_layer.forward(score, t)
        return loss

    def backward(self, dout=1):
        dout = self.loss_layer.backward(dout)
        for layer in reversed(self.layers):
            dout = layer.backward(dout)
        return dout


In [6]:
x = np.random.randn(10, 2)
model = TwoLayersNet(2, 4, 3)
s = model.predict(x)
print(s)


[[ 0.76065908 -0.36741883  0.10238995]
 [ 0.25463967 -0.42511882  0.31959841]
 [-0.18650807 -0.56299782  0.7001589 ]
 [-0.34651606 -0.71825485  0.54477786]
 [-0.21747417 -0.56905373  0.77214697]
 [ 0.03202724 -0.50017115  0.44281184]
 [ 0.58533649 -0.27490116  0.40471138]
 [ 0.986053   -0.16679866  0.08898377]
 [-0.27461834 -0.57490921  0.91441923]
 [ 0.17480354 -0.46578586  0.33985754]]
